# Generated by Django 4.1.7 on 2023-03-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='server_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
